name: dbc
channels:
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - absl-py
  - pyparsing
  - pip:
    - gym=0.23.1
    - termcolor
    - git+https://github.com/google-deepmind/dm_control.git
    - git+https://github.com/denisyarats/dmc2gym.git
    - opencv-python
    - pillow
    - scikit-image
    - scikit-video
    - tb-nightly
    - tqdm
    - imageio
    - imageio-ffmpeg
    - pygame
    - networkx
    - dotmap
