name: dbc
channels:
  - defaults
dependencies:
  - python=3.11
  - absl-py
  - pyparsing
  - pip:
    - numpy==1.26.4
    - gym==0.23.1
    - six
    - opencv-python-headless==4.12.0.88
    - termcolor
    - git+https://github.com/google-deepmind/dm_control.git
    - git+https://github.com/denisyarats/dmc2gym.git
    - opencv-python
    - pillow
    - scikit-image
    - scikit-video
    - tb-nightly
    - tqdm
    - imageio
    - imageio-ffmpeg
    - pygame
    - networkx
    - dotmap